In [44]:
import numpy as np
import pandas as pd

In [45]:
names = [
    'Class',
    'Alcohol',
 	'Malic acid',
 	'Ash',
	'Alcalinity of ash  ',
 	'Magnesium',
	'Total phenols',
 	'Flavanoids',
 	'Nonflavanoid phenols',
 	'Proanthocyanins',
	'Color intensity',
 	'Hue',
 	'OD280/OD315 of diluted wines',
 	'Proline'
]

In [46]:
path = "./wine_dataset/wine.data"
df = pd.read_csv(path, header=None, names=names)
df

,Class,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [47]:
df_by_class_mean = df.groupby('Class').apply('mean')
df_by_class_mean

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
Class,,,,,,,,,,,,,
1,13.744746,2.010678,2.455593,17.037288,106.338983,2.840169,2.982373,0.290000,1.899322,5.528305,1.062034,3.157797,1115.711864
2,12.278732,1.932676,2.244789,20.238028,94.549296,2.258873,2.080845,0.363662,1.630282,3.086620,1.056282,2.785352,519.507042
3,13.153750,3.333750,2.437083,21.416667,99.312500,1.678750,0.781458,0.447500,1.153542,7.396250,0.682708,1.683542,629.895833

In [48]:
test1 = df.groupby('Class').transform('mean')
test1

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,13.744746,2.010678,2.455593,17.037288,106.338983,2.840169,2.982373,0.2900,1.899322,5.528305,1.062034,3.157797,1115.711864
1,13.744746,2.010678,2.455593,17.037288,106.338983,2.840169,2.982373,0.2900,1.899322,5.528305,1.062034,3.157797,1115.711864
2,13.744746,2.010678,2.455593,17.037288,106.338983,2.840169,2.982373,0.2900,1.899322,5.528305,1.062034,3.157797,1115.711864
3,13.744746,2.010678,2.455593,17.037288,106.338983,2.840169,2.982373,0.2900,1.899322,5.528305,1.062034,3.157797,1115.711864
4,13.744746,2.010678,2.455593,17.037288,106.338983,2.840169,2.982373,0.2900,1.899322,5.528305,1.062034,3.157797,1115.711864
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.153750,3.333750,2.437083,21.416667,99.312500,1.678750,0.781458,0.4475,1.153542,7.396250,0.682708,1.683542,629.895833
174,13.153750,3.333750,2.437083,21.416667,99.312500,1.678750,0.781458,0.4475,1.153542,7.396250,0.682708,1.683542,629.895833
175,13.153750,3.333750,2.437083,21.416667,99.312500,1.678750,0.781458,0.4475,1.153542,7.396250,0.682708,1.683542,629.895833
176,13.153750,3.333750,2.437083,21.416667,99.312500,1.678750,0.781458,0.4475,1.153542,7.396250,0.682708,1.683542,629.895833
177,13.153750,3.333750,2.437083,21.416667,99.312500,1.678750,0.781458,0.4475,1.153542,7.396250,0.682708,1.683542,629.895833

In [49]:
added_column = df.copy()

added_column['Hue_classif'] = df['Hue'].map(lambda x: 'High' if x > 1 else 'Low')
added_column

,Class,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Hue_classif
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,High
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,High
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,High
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,Low
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,Low
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,Low
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,Low
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,Low
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,Low

In [50]:
dict = {
    'High': 1,
    'Low': 0
}
df['Hue_classif'] = added_column['Hue_classif'].map(dict)
df

,Class,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Hue_classif
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,0
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,0
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,0
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,0
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,0

In [51]:
df_copy = df.copy()
df_copy = df_copy.drop('Class', axis=1)
df_copy

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Hue_classif
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,0
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,0
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,0
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,0
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,0

In [52]:
df.index

RangeIndex(start=0, stop=178, step=1)

In [53]:
df_copy = df.copy()
df_copy = df_copy.drop('Class', axis=1)
df_copy

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Hue_classif
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,0
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,0
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,0
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,0
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,0

In [54]:
df_copy.mean()

Alcohol                          13.000618
Malic acid                        2.336348
Ash                               2.366517
Alcalinity of ash                19.494944
Magnesium                        99.741573
Total phenols                     2.295112
Flavanoids                        2.029270
Nonflavanoid phenols              0.361854
Proanthocyanins                   1.590899
Color intensity                   5.058090
Hue                               0.957449
OD280/OD315 of diluted wines      2.611685
Proline                         746.893258
Hue_classif                       0.460674
dtype: float64

In [55]:
df_copy - df_copy.mean()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Hue_classif
0,1.229382,-0.626348,0.063483,-3.894944,27.258427,0.504888,1.03073,-0.081854,0.699101,0.58191,0.082551,1.308315,318.106742,0.539326
1,0.199382,-0.556348,-0.226517,-8.294944,0.258427,0.354888,0.73073,-0.101854,-0.310899,-0.67809,0.092551,0.788315,303.106742,0.539326
2,0.159382,0.023652,0.303483,-0.894944,1.258427,0.504888,1.21073,-0.061854,1.219101,0.62191,0.072551,0.558315,438.106742,0.539326
3,1.369382,-0.386348,0.133483,-2.694944,13.258427,1.554888,1.46073,-0.121854,0.589101,2.74191,-0.097449,0.838315,733.106742,-0.460674
4,0.239382,0.253652,0.503483,1.505056,18.258427,0.504888,0.66073,0.028146,0.229101,-0.73809,0.082551,0.318315,-11.893258,0.539326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0.709382,3.313652,0.083483,1.005056,-4.741573,-0.615112,-1.41927,0.158146,-0.530899,2.64191,-0.317449,-0.871685,-6.893258,-0.460674
174,0.399382,1.573652,0.113483,3.505056,2.258427,-0.495112,-1.27927,0.068146,-0.180899,2.24191,-0.257449,-1.051685,3.106742,-0.460674
175,0.269382,1.943652,-0.106517,0.505056,20.258427,-0.705112,-1.33927,0.068146,-0.240899,5.14191,-0.367449,-1.051685,88.106742,-0.460674
176,0.169382,0.253652,0.003483,0.505056,20.258427,-0.645112,-1.34927,0.168146,-0.130899,4.24191,-0.357449,-0.991685,93.106742,-0.460674
177,1.129382,1.763652,0.373483,5.005056,-3.741573,-0.245112,-1.26927,0.198146,-0.240899,4.14191,-0.347449,-1.011685,-186.893258,-0.460674

In [56]:
abs(df_copy - df_copy.mean())

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Hue_classif
0,1.229382,0.626348,0.063483,3.894944,27.258427,0.504888,1.03073,0.081854,0.699101,0.58191,0.082551,1.308315,318.106742,0.539326
1,0.199382,0.556348,0.226517,8.294944,0.258427,0.354888,0.73073,0.101854,0.310899,0.67809,0.092551,0.788315,303.106742,0.539326
2,0.159382,0.023652,0.303483,0.894944,1.258427,0.504888,1.21073,0.061854,1.219101,0.62191,0.072551,0.558315,438.106742,0.539326
3,1.369382,0.386348,0.133483,2.694944,13.258427,1.554888,1.46073,0.121854,0.589101,2.74191,0.097449,0.838315,733.106742,0.460674
4,0.239382,0.253652,0.503483,1.505056,18.258427,0.504888,0.66073,0.028146,0.229101,0.73809,0.082551,0.318315,11.893258,0.539326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0.709382,3.313652,0.083483,1.005056,4.741573,0.615112,1.41927,0.158146,0.530899,2.64191,0.317449,0.871685,6.893258,0.460674
174,0.399382,1.573652,0.113483,3.505056,2.258427,0.495112,1.27927,0.068146,0.180899,2.24191,0.257449,1.051685,3.106742,0.460674
175,0.269382,1.943652,0.106517,0.505056,20.258427,0.705112,1.33927,0.068146,0.240899,5.14191,0.367449,1.051685,88.106742,0.460674
176,0.169382,0.253652,0.003483,0.505056,20.258427,0.645112,1.34927,0.168146,0.130899,4.24191,0.357449,0.991685,93.106742,0.460674
177,1.129382,1.763652,0.373483,5.005056,3.741573,0.245112,1.26927,0.198146,0.240899,4.14191,0.347449,1.011685,186.893258,0.460674

In [57]:
df_copy.std()

Alcohol                           0.811827
Malic acid                        1.117146
Ash                               0.274344
Alcalinity of ash                 3.339564
Magnesium                        14.282484
Total phenols                     0.625851
Flavanoids                        0.998859
Nonflavanoid phenols              0.124453
Proanthocyanins                   0.572359
Color intensity                   2.318286
Hue                               0.228572
OD280/OD315 of diluted wines      0.709990
Proline                         314.907474
Hue_classif                       0.499857
dtype: float64

In [58]:
n = 2
res = abs(df_copy - df_copy.mean() >= 2 * df_copy.std())
res

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Hue_classif
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,False,True,False,False,False,False,False,False,False,False,False,False,False,False
174,False,False,False,False,False,False,False,False,False,False,False,False,False,False
175,False,False,False,False,False,False,False,False,False,True,False,False,False,False
176,False,False,False,False,False,False,False,False,False,False,False,False,False,False
177,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [59]:
res.sum()

Alcohol                         2
Malic acid                      9
Ash                             3
Alcalinity of ash               5
Magnesium                       6
Total phenols                   2
Flavanoids                      1
Nonflavanoid phenols            5
Proanthocyanins                 9
Color intensity                 9
Hue                             3
OD280/OD315 of diluted wines    0
Proline                         6
Hue_classif                     0
dtype: int64

In [60]:
columns = res.columns
columns

Index(['Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash  ', 'Magnesium',
       'Total phenols', 'Flavanoids', 'Nonflavanoid phenols',
       'Proanthocyanins', 'Color intensity', 'Hue',
       'OD280/OD315 of diluted wines', 'Proline', 'Hue_classif'],
      dtype='object')

In [62]:
index_drop = res[res[columns].eq(True).any(axis=1)]
index_drop

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Hue_classif
2,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,True,False
5,False,False,False,False,False,False,False,False,False,False,False,False,True,False
8,True,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,True,False
13,True,False,False,False,False,False,False,False,True,False,False,False,False,False
14,False,False,False,False,False,False,False,False,True,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False,True,False
25,False,False,True,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,True,False
33,False,False,False,False,True,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,True,False,False,False,False,False
52,False,False,False,False,False,True,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,True,False,False,False,False,False,False
64,False,False,False,False,False,False,False,False,False,False,True,False,False,False
69,False,False,False,False,True,False,False,False,False,False,False,False,False,False
73,False,False,False,True,True,False,False,False,False,False,False,False,False,False
78,False,False,False,False,True,False,False,False,True,False,False,False,False,False
95,False,False,False,False,True,False,False,False,True,False,False,False,False,False
96,False,False,False,False,True,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,True,False,True,False,False,False
105,False,False,False,False,False,False,False,True,False,False,False,False,False,False
110,False,False,False,False,False,False,False,False,True,False,False,False,False,False
112,False,False,True,False,False,False,False,False,False,False,False,False,False,False
115,False,False,False,False,False,False,False,False,False,False,True,False,False,False
121,False,False,True,True,False,False,True,False,False,False,False,False,False,False
122,False,False,False,True,False,False,False,False,False,False,False,False,False,False
123,False,True,False,False,False,False,False,False,False,False,False,False,False,False
124,False,False,False,False,False,False,False,False,True,False,False,False,False,False
127,False,False,False,True,False,False,False,False,False,False,False,False,False,False
135,False,False,False,False,False,False,False,True,False,False,False,False,False,False
136,False,True,False,False,False,False,False,False,False,False,False,False,False,False
137,False,True,False,False,False,False,False,True,False,False,False,False,False,False
143,False,True,False,False,False,False,False,False,False,False,False,False,False,False
146,False,True,False,False,False,False,False,False,False,False,False,False,False,False
147,False,True,False,False,False,False,False,False,False,False,False,False,False,False
151,False,False,False,False,False,False,False,False,False,True,False,False,False,False
153,False,False,False,False,False,False,False,False,False,True,False,False,False,False
155,False,True,False,False,False,False,False,False,False,False,False,False,False,False
157,False,False,False,True,False,False,False,True,False,False,False,False,False,False
158,False,False,False,False,False,False,False,False,False,True,False,False,False,False
159,False,False,False,False,False,False,False,False,False,True,False,False,False,False
166,False,False,False,False,False,False,False,False,False,True,False,False,False,False
167,False,False,False,False,False,False,False,False,False,True,False,False,False,False
169,False,True,False,False,False,False,False,False,False,False,False,False,False,False
171,False,False,False,False,False,False,False,False,False,True,False,False,False,False
172,False,False,False,False,False,False,False,False,False,True,False,False,False,False
173,False,True,False,False,False,False,False,False,False,False,False,False,False,False
175,False,False,False,False,False,False,False,False,False,True,False,False,False,False